akeeba/akeebasubs

- component/frontend/views/subscriptions/tmpl/default.php
In component/frontend/views/subscriptions/tmpl/default.php
line 106:
<?php echo $this->escape($subscription->title)?>
does not get the localized version of the Level title.
It is displaying the translated version if replaced with:
<?php echo $this->escape($level->title)?>
> Subscriptions View: Level title not getting localized

- component/backend/config.xml
- component/backend/models/invoices.php
- component/backend/models/taxconfigs.php
When a business from the same country as the shop owner's country registers (and both are from the EU) the integrated invoicing is adding the VAT liability information at the bottom of the invoice which is not correct.(the business is being charged VAT and they should not pay VAT again).
That is why I've created a new hidden parameter invoices_country. This parameter is auto-populated when the tax wizard is ran.
Then in the invoicing model we compare the shop owner's country to the current user's country and if all the conditions match, then we'll add the VAT liability info to the invoice. 
Note: the tax wizard needs to be run again. Otherwise the invoices_country parameter will be empty and we'll experience the old behavior.
> VAT Liability for businesses from the same country as the shop owner country is now not written

- documentation/akeebasubs-guide.xml
Bad link to Paypal Express Checkout API in documentation. The existing link goes to a non-existent location.
> Bad link in documentation

- component/backend/views/subscriptions/tmpl/default.php
The business name field is called businessname and not business_name. This fixes that and makes the data to show in the list.
> Typo in business name field

- plugins/akeebasubs/slavesubs/slavesubs.php
This change also fixes the issue with the parent sub not saving the Slave Sub IDs to the parent sub params in the database.
> Eliminate duplicated code for creating new slave subs.

- plugins/akeebasubs/slavesubs/slavesubs.php
This section of code was looking in the wrong variable for existing slave users breaking the the extend subscription for existing slave subs.
see line 400 and 401 for explanation of $previous and $current variables
The opening check if statement was also broke, as it should check for existing slaveusers being in the merged ($current+$previous) $list array and the $previous array.
> Slave is still here, use $previous not $current

- plugins/akeebasubs/slavesubs/slavesubs.php
-Utilize the "copySubscriptionInformation" to sync the slave with the parent on modification. We do not care what the state of the slave is in for syncing, just that the slavesub should still exist. 
-Added a return in the copySubscriptionInformation to keep track of what slave sub was modified so the ID can continue to be stored in the parent sub
-Corrected an if statement that on second look should be checking previous vs current (is the user in both to proceed)
> Slave is still here, just sync with the parent sub

- plugins/akeebasubs/slavesubs/slavesubs.php
input parameter to Save the new slave subscription record is a Username not the user ID; corrected at line 400
> incorrect use of input params for createSlaveSub

- plugins/akeebasubs/slavesubs/slavesubs.php
no need to "$table->reset();" resetting the table index will point to the last saved slave subscription rather than the parent subscription (except when creating a slavesub, since we are creating new table rows)
no need to work with the whole table when a single item will suffice
uncomment the if !dirty "return"
(hunting for the cause of a 403 error in the front end user interface when a subscription is created with an addon user. Getting the wrong sub ID in the URL, rather than the parent ID I keep getting the slave sub ID)
> miscellaneous code changes (on the hunt for cause of 403)

- plugins/akeebasubs/slavesubs/slavesubs.php
proposed change fixes a 403 error that occurred when a user saves a subscription with a slave sub. The return URL on subscribing was receiving the slave sub ID rather than the current user's (parent) subscription ID
> resolution to 403 error for slave subs

- component/backend/CustomField/Pricedropdown.php
- plugins/akeebasubs/customfields/customfields.php
Proposed fix for "Warning: array_key_exists() expects parameter 2 to be array, null given in /administrator/components/com_akeebasubs/CustomField/Pricedropdown.php on line 34"
> if the cache is null, create a null array key for subscriptionlevel

- component/backend/Controller/Subscriptions.php
The following error occurs when you click "publish" for a user subscription that has a subscription level with custom fields and is currently set to "enabled, no" 
Fatal error: Class 'Akeeba\Subscriptions\Admin\Controller\Inflector' not found in /administrator/components/com_akeebasubs/Controller/Subscriptions.php on line 42
proposed change fixes the error
> Fatal error: Class not found

- README.md
Some helpful hints gleaned from personal experience that a new developer wanting to make a build would like to know. 
- elevated command prompt for xampp can be accomplished by modify your xampp_shell.bat file to run as administrator by forced UAC http://superuser.com/questions/788924/is-it-possible-to-automatically-run-a-batch-file-as-administrator or http://stackoverflow.com/questions/7044985/how-can-i-auto-elevate-my-batch-file-so-that-it-requests-from-uac-administrator 
- see also adding git to xampp https://community.apachefriends.org/f/viewtopic.php?f=16&t=56990
- modify the important note for 'creating a dev release installation package' to be more clear that running the `git pull` and `phing git`commands are part of creating a FOF package before building an Akeeba Subscriptions …
> improvements to package build instructions

- plugins/akeebasubs/slavesubs/slavesubs.php
This check is now redundant with the check that immediately proceeded it.
> Remove redundant "if (empty($params)) check"

- plugins/akeebasubs/agreetoeu/agreetoeu.php
- plugins/akeebasubs/agreetotos/agreetotos.php
Proposed change deals with PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /akeebasubs/agreetotos/agreetotos.php on line 176
> If $custom is null, or is not an array... make $custom an array

- component/frontend/View/Subscriptions/tmpl/default.php
Fatal error: Class 'AkeebasubsHelperCparams' not found in /components/com_akeebasubs/View/Subscriptions/tmpl/default.php on line 23
ComponentParams::getParam replaces AkeebasubsHelperCparams::getParam
> Class 'AkeebasubsHelperCparams' not found

- plugins/akeebasubs/slavesubs/slavesubs.php
As per F0F documentation, "// If you forget the clone you will spend some not-so-fun hours debugging erratic Behavior" (Yep, that happened)
This PR fixes the issue with lines 433 and 434 where the variables $from and $to were resulting in the same record being passed to copySubscriptionInformation. With this PR slave subs are finally valid and active in AS 4. For good measure, following the F0F documentation all instances of F0FModel::getTmpInstance were changed to "clone F0FModel::getTmpInstance()" 
https://www.akeebabackup.com/documentation/fof/foftable-simpleorm.html
> Add clone before F0FModel::getTmpInstance

- plugins/akeebasubs/slavesubs/slavesubs.php
Apparently clone is causing some issues in this one function.
PHP Fatal error:  __clone method called on non-object in /plugins/akeebasubs/slavesubs/slavesubs.php on line 497
PHP Fatal error:  Call to a member function count() on a non-object in /plugins/akeebasubs/slavesubs/slavesubs.php on line 506
> Remove clone from F0FModel in function onAKUserRefresh

- component/backend/CustomField/Date.php
There was a fatal error in front end subscription form: 
Fatal error: Class 'Akeeba\Subscriptions\Admin\CustomField\JHTML' not found in [joomla]/administrator/components/com_akeebasubs/CustomField/Date.php on line 49
> Added 'use' Statement to include JText

- component/backend/Model/Subscriptions.php
When trying to use the filter in the backend one runs into a wrong query.
> fix wrong query in filter for sub view in backend

- plugins/akeebasubs/slavesubs/slavesubs.php
Insurance against cases where the records should not be copied. 
(These shouldn't happen, but if they do...)
- If it's the same record, there is nothing to do
- Don't copy over if the `$to` record has slaveusers
- Don't copy over if the `$to` subscription has slavesubs_ids
> Let's make sure we are not copying improper rows

- component/backend/Model/Subscriptions.php
Line 1030 results in a "Strict standards: Only variables should be passed by reference" error
Signed-off-by: Craig Phillips <craig@craigphillips.biz>
> Workaround strict standards error

- component/backend/Helper/EUVATInfo.php
Make two attempts to validate EU VAT number with SoapClient and if it has failed then make two attempts to fetch webpage with validation result.
> VIES validation improved

- plugins/akpayment/paypal/paypal.php
calculate duration based on publish date because it might have been changed by plugins event onValidateSubscriptionLength
> PayPal recurring subscription duration fixed

- component/backend/assets/akpayment.php
In PayPal plugin on recurring payment there is create param recurring_id on line
https://github.com/akeeba/akeebasubs/blob/4.x/plugins/akpayment/paypal/paypal.php#L321
which is being discarded in method plgAkpaymentAbstract::fixSubscriptionDates
> Fix replacing params when saving subscription in payment plugin

- plugins/akpayment/paypal/paypal.php
First initial PayPal payment have to match the gross amount. The recurring amount should be compared only for recurring payments. When it is an initial payment then the subscription status is NEW and in this case the gross amount have to be used. When there is a recurring amount and it is a second payment (first renewal) then the recurring amount should be used. For the third payment we will use the gross amount as the recurring amount will be set to 0 after the second payment.
This have fixed an issue when: 
- first payment gross amount is lower than recurring amount for next payments
- and first cycle is shorter than recurring cycle
> Do not use recurring amount for the first initial payment

- build/templates/pkg_akeebasubs.xml
CLI is removed but there is a following line of code in /build/templates/pkg_akeebasubs.xml
```
<file type="file" id="file_akeebasubs">file_akeebasubs.zip</file>
```
Although build is successful, package installation fails.
Please remove the code.
> Update pkg_akeebasubs.xml since cli removed

- plugins/akpayment/paypal/paypal.php
When a recurring subscription has been suspended, then there is an option on PayPal to charge outstanding payment if the customer has the cash on his credit card. This generates a new transaction type: recurring_payment_outstanding_payment
```
option com_akeebasubs
view callback
paymentmethod paypal
mc_gross 21.42
outstanding_balance 0.00
next_payment_date 03:00:00 Aug 22, 2017 PDT
protection_eligibility Ineligible
tax 0.00
payer_id xxxxxxxxxxxxx
payment_date 18:24:20 Sep 01, 2016 PDT
payment_status Completed
product_name Contact Form WP updates and support 12M R
charset windows-1250
recurring_payment_id I-xxxxxxxxxxxxxxx
first_name Jane
mc_fee 0.84
notify_version 3.8
custom 1111111
payer_status verified
currency_code EUR
business xxxxxx@perfect-web.co
verify_sign …
```
> Handle unsuspended recurring payment

- component/media/js/signup.js
A wrong ID is used, which causes the VAT container not to show when opening the subscribe page. ("Prices include VAT x%")
> VAT rate does not show on subscribe page

- component/frontend/View/UserInfo/Html.php
There is an error when I try to edit user subscription profile. It is missing **_getFieldValue()_** in _components/com_akeebasubs/View/UserInfo/Html.php_
___
**screenshot 1** (creating menu item)
___
**screenshot 2** (opening the menu item for editing subscription profile)
___
**screenshot 3** (error message)
> Added method getFieldValue() to UserInfo\Html

- component/media/js/signup.js
If you change to an EU VAT country, the business fields appear even if the customer selected to not be a business customer.
> fixes the visibility of the business fields.

- component/frontend/View/Level/tmpl/default_fields.blade.php
During subscription the "Do you have an account already?" is not pointing to the menu item of type "Login". This pr changes that.
Strangely on akeebabackup.com, the link is correct. So honestly I'm not sure if I did pick the wrong menu item.
> Link to login view when subscribing

- plugins/akpayment/2conew/2conew.php
Order id is sent to 2checkout using variable "merchant_order_id" and 2checkout returns the order id in INS in the variable "vendor_order_id" and not in "merchant_order_id".
The plugin code expects the order id in the variable "merchant_order_id" which is not sent by 2checkout in INS (send as "vendor_order_id") which is causing trouble in auto confirmation
I referred the INS guide provided by 2checkout
https://www.2checkout.com/static/va/documentation/INS/INS_User_Guide_04_08_2009.pdf
> orders are not auto confirmed after successfull payment by 2conew payment plugin #148

- component/backend/config.xml
- component/frontend/Model/Subscribe/Validation/Password.php
- translations/component/backend/en-GB/en-GB.com_akeebasubs.ini
This PR adds the same checks that Joomla\CMS\Form\Rule\PasswordRule implements for the normal com_users component.
> Add Password Checks from user Component params
