modules/site/aktaxcountry/mod_aktaxcountry.php
Fatal error: Cannot use object of type JRegistry as array in mod_aktaxcountry.php
=> Fatal error: Cannot use object of type JRegistry as array in mod_aktaxcountry.php

plugins/akeebasubs/slavesubs/slavesubs.php
slaveusers and the new parentsub_id should not be copied
=> unset params that should not be copied

plugins/akeebasubs/slavesubs/slavesubs.php
add comments to explain the functions, when they are used and the input parameters for the functions.
=> add comments for function explinations

plugins/akeebasubs/slavesubs/slavesubs.php
add required processor_key as a random number, set state to completed, and enable the subscription.
consideration should be placed on possibly using the function copySubscriptionInformation in the future to ensure the slave is enabled and synced with the parent sub on creation.
=> slave subs are not "valid" since they are not enabled

component/backend/config.xml, component/frontend/View/Subscriptions/tmpl/default.php, translations/component/backend/en-GB/en-GB.com_akeebasubs.ini
also fixed a typo in component/frontend/View/Subscriptions/tmpl/default.php "use" statement
=> Add the pretty pictures for the customers from AK4 PR #143

component/script.akeebasubs.php, component/script.com_akeebasubs.php
AS 5 "This version of Akeeba Subscriptions is written on FOF 3. It requires Joomla! 3.4 or later and PHP 5.4.0 or later."
=> Update Joomla version to 3.4 as per the documentation

component/backend/CustomField/Date.php
- correction to pull request #152
=> JText was included twice, one should have been JHtml

component/frontend/views/levels/tmpl/awesome.php, component/frontend/views/levels/tmpl/default.php, component/frontend/views/levels/tmpl/strappy.php
- Fixes the VAT display option introduced in 4.2
=> VAT rate was displaying regardless of show VAT setting

plugins/akeebasubs/recaptcha/recaptcha.php
Added public scope modifiers to onSubscriptionFormRender and onValidate
=> No scope modifier specified for functions

component/backend/fields/akeebasubsinvoicenumber.php
Undefined variable was used to show invoice display_number, fixed with correct variable
=> Invoice display number

component/backend/fields/akeebasubsinvoiceactions.php
When filter form is submitted in invoices view then JavaScript with Modal is not being loaded.
=> Load Modal JS

component/frontend/Model/Subscribe.php
As the title says - fixes issue #166
=> fixes issue #166

CHANGELOG, component/backend/Helper/Select.php, component/backend/Model/Reports.php, component/backend/View/Reports/tmpl/invoices_controls.php, component/backend/View/Reports/tmpl/invoices_vatmoss.php, translations/component/backend/en-GB/en-GB.com_akeebasubs.ini
=> Filter reports by invoice template

CHANGELOG, component/backend/Helper/Message.php, component/backend/assets/elements/akeebasubscurrencies.php, component/backend/config.xml, component/backend/sql/xml/mysql.xml, component/backend/sql/xml/postgresql.xml, component/frontend/Model/Subscribe.php, translations/component/backend/en-GB/en-GB.com_akeebasubs.ini
=> Alternate currency

component/backend/Model/MakeCoupons.php, component/backend/View/MakeCoupons/Html.php
Grabs the session object through the container object
=> Get the session object through the container

plugins/akpayment/paypal/paypal.php
Handle payment states: Reversed, Canceled_Reversal, Refunded
=> Handle PayPal refunds

plugins/akpayment/paypal/paypal.php
Handle recurring payments for levels with sign-up fee
=> Handle recurring payments

component/backend/helpers/euvatinfo.php
Make two attempts to validate EU VAT number with SoapClient and if it has failed then make two attempts to fetch webpage with validation result.
=> VIES validation improved

plugins/akpayment/paypal/paypal.php
A quick fix after first real recurring payment
=> PayPal - Fix invoice for old subscription

plugins/akpayment/paypal/paypal.php
When pull request with AkpaymentBase::fixSubscriptionDates will be merged then cancel action would redirect directly to subscription profile on PayPal instead to all subscription from given merchant
=> PayPal direct redirect to cancel recurring payment

plugins/akeebasubs/kunena/kunena.php, plugins/akeebasubs/kunena/kunena.xml, plugins/akeebasubs/kunena/language/index.html, plugins/akeebasubs/kunena/tmpl/default.php, translations/plugins/akeebasubs/kunena/en-GB/en-GB.plg_akeebasubs_kunena.ini, translations/plugins/akeebasubs/kunena/en-GB/en-GB.plg_akeebasubs_kunena.sys.ini
Hi Nicholas, this is the patch to update Kunena plugin to support Akeeba Subs 5, let me know if I miss anything.
=> Update Kunena plugin to support Akeeba Subs 5

plugins/akpayment/paypal/paypal.php
PayPal says that IPN endpoint should also be updated for forward compatibility, more info at https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US
=> Update IPN endpoint

plugins/akeebasubs/slavesubs/slavesubs.php
Yes I know I know. I'm pedantic
=> Comment type

component/backend/sql/xml/mysql.xml
Micro bug, annoying consequences :)  Credit note template with ID 1 was constantly reverting to default one
=> Fix typo causing reverts to default template

plugins/system/asexpirationnotify/asexpirationnotify.php, plugins/system/asfixrenewalsflag/asfixrenewalsflag.php, plugins/system/asfixrenewalsflag/asfixrenewalsflag.xml, plugins/system/asfixrenewalsflag/language/en-GB/en-GB.plg_system_asfixrenewalsflag.ini, plugins/system/asfixrenewalsflag/language/en-GB/en-GB.plg_system_asfixrenewalsflag.sys.ini
=> Fix contact emails on subscriptions with renewals

plugins/akeebasubs/agreetoeu/agreetoeu.php
some copy/paste problems fixed
=> some things in agreetoeu plugin changed I found being strange ;)

component/backend/Model/Coupons.php, component/backend/sql/xml/mysql.xml, component/script.com_akeebasubs.php
Removed references to Akeeba Subscriptions Users
Close #344
=> Remove users
